sudo: required

services:
  - docker

language: node_js
node_js:
  - '9'

cache:
  yarn: true
  directories:
  - node_modules

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose pull
  - npx yarn install
  - docker pull hadolint/hadolint

script:
  - npx yarn dev:docker:db
  - npx yarn dev:lint
  - npx yarn test
  - docker run --rm -i hadolint/hadolint < Dockerfile

notifications:
  slack: ambrosus:ybmTQyso2XmAp6SM9NQPhdl2
