dist: trusty
language: node_js
cache:
  yarn: true
  directories:
  - node_modules
services:
  - mongodb
notifications:
  slack: ambrosus:ybmTQyso2XmAp6SM9NQPhdl2
node_js:
  - '9'
install:
  - yarn install
  - yarn build:contracts
script:
  - mongod --version
  - yarn test
  - yarn dev:lint
env:
  global:
    - MONGODB_URI="mongodb://localhost/ambrosus_gateway_test"
    - PORT=9876
