swagger: "2.0"
info:
  description: |
    Welcome to Ambrosus Node API Documentation.  

    ### Authentication
    Before you can start interacting with API you need to create an account. An account is a pair: address and secret.

    Each state-modifying call needs to have the `content.idData.createdBy` field with creator address and one of two:
    * A body field `content.signature`. It is generated with ethereum sign function from the serialized `content.data` object. Serialisation algorithm will be described in separate section.
    * A http authoristaion header `AMB ,,,`: You can supply your secret to API and gateway will calculate the signature for you. __Warning__: This is only allowed in development and testing environment. We strongly recommend against using it in a production environment.

    ### Immutability

    __Note:__ All data is immutable, therefore, you will not find update or delete calls.

  version: "0.0.1"
  title: "Ambrosus Node API"
  contact:
    email: "marek@ambrosus.com"
host: 'network.ambrosus.com'
tags:
- name: "Account"
  description: |
    API for creating accounts, supplement to ethereum account creation. 
schemes:
- "https"
paths:
  /accounts:
    post:
      tags:
      - "Account"
      summary: "Create account"
      description: "Account is a pair - a public identifer `address` (compatible with ethereum address) and a `secret` (compatible with ethereum private key)."
      operationId: "createAccount"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        201:
          description: "Created."
          schema:
            type: "object"
            properties:
              address:
                type: "string"
                example: "0x162a44701727a31f457a53801cd181cd38eb5bbd"
              secret:
                type: "string"
                example: "0x17d08f5fe8c77af811caa0c9a187e668ce3b74a99acc3f6d976f075fa8e0be55"