# Dockerfile for setting up a local development environment. Note that this
# should not be used for production.
version: "3"
services:
  db:
    image: mongo:4.0.9
    ports:
      - '27017:27017'
    container_name: "db"

  parity:
    container_name: "parity"
    image: parity/parity:v2.4.5
    # Parity by default only exposes it's API on localhost. For it to be
    # accessible from the other containers we need --unsafe-expose
    command: ['--chain', 'dev', '--unsafe-expose']
    ports:
      - '8545:8545'

  hermes_server:
    image: quay.io/ambrosus/ambrosus-node-extended
    ports:
      - '3000:3000'
    volumes:
      - ~/ambrosus-nop:/opt/hermes
    command: ['yarn', 'dev:start']
    network_mode: host
    container_name: "hermes_extended"
